### ISSUE TITLE
Desativar auto toggle da dialog na navegação

### ISSUE THREAD

**Issue by vtrpldn** [stone-payments/pos-mamba-sdk-docs#9]
https://mambasdkdocs-rwuaxalenr.now.sh/components/dialog

O dialog abre sozinho quando você acessa o link pela navegação e carrega 100vw

**Comment by kaisermann** [comment]
Só tirar o `isOpen={true}` [daqui](https://github.com/stone-payments/pos-mamba-sdk/blob/develop/packages/components/Dialog/example/Example.html#L41)

**Comment by jacksongarcia** [comment]
https://github.com/stone-payments/pos-mamba-sdk/pull/164
